"""Interactive ``init`` wizard for plantsim-copilot-mcp.

Walks a new user through:

1. KB roots — markdown directories to index for ``search_help`` / ``get_api``
2. Optional fullmd source (``pts_help_2504_fullmd/*.md``) and chapters
3. Optional default ``.psfm`` project for ``find_method`` / ``find_callers``
4. Index output directory (defaults to ``~/.plantsim-agent/indices``)

Writes the result to ``~/.plantsim-agent/config.toml`` (or wherever
``$PLANTSIM_AGENT_HOME`` points), then optionally runs the indexers.

Designed to be importable so the CLI subcommand and a future
``scripts/build_kb.py`` shim share one implementation. Supports a
``--non-interactive`` mode for cold-install tests.
"""

from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

from .config import CONFIG_FILENAME, Paths, agent_home


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class WizardAnswers:
    """Everything the wizard collects, ready to be written to config.toml."""

    help_kb_roots: list[Path] = field(default_factory=list)
    fullmd_src: Path | None = None
    fullmd_chapters: list[int] = field(default_factory=lambda: [11, 12, 13, 15])
    default_project: Path | None = None
    index_dir: Path = field(default_factory=lambda: agent_home() / "indices")


# ---------------------------------------------------------------------------
# TOML writer (stdlib has tomllib reader but no writer)
# ---------------------------------------------------------------------------


def _toml_path(p: Path) -> str:
    """Render ``Path`` as a TOML basic string with forward slashes."""
    return '"' + str(p).replace("\\", "/").replace('"', r"\"") + '"'


def render_config_toml(ans: WizardAnswers) -> str:
    """Render the wizard answers as a config.toml document."""
    lines: list[str] = [
        "# Generated by `plantsim-copilot-mcp init`",
        "# Edit by hand or rerun the wizard to update.",
        "",
        "[paths]",
        f"index_dir = {_toml_path(ans.index_dir)}",
    ]
    if ans.help_kb_roots:
        rendered = ", ".join(_toml_path(p) for p in ans.help_kb_roots)
        lines.append(f"help_kb_roots = [{rendered}]")
    if ans.fullmd_src is not None:
        lines.append(f"fullmd_src = {_toml_path(ans.fullmd_src)}")
    if ans.fullmd_chapters:
        rendered_ch = ", ".join(str(c) for c in ans.fullmd_chapters)
        lines.append(f"fullmd_chapters = [{rendered_ch}]")
    if ans.default_project is not None:
        lines.append(f"default_project = {_toml_path(ans.default_project)}")
    lines.append("")
    return "\n".join(lines)


def write_config(ans: WizardAnswers, config_path: Path) -> None:
    """Write ``config.toml`` to ``config_path``, creating parents."""
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(render_config_toml(ans), encoding="utf-8")


# ---------------------------------------------------------------------------
# Prompt helpers (only used in interactive mode)
# ---------------------------------------------------------------------------


def _prompt(question: str, default: str | None = None) -> str:
    """Ask one line. Empty answer falls back to ``default`` (if given)."""
    suffix = f" [{default}]" if default else ""
    raw = input(f"{question}{suffix}: ").strip()
    if not raw and default is not None:
        return default
    return raw


def _prompt_yes_no(question: str, default: bool = True) -> bool:
    suffix = "[Y/n]" if default else "[y/N]"
    raw = input(f"{question} {suffix}: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")


def _prompt_path(
    question: str,
    *,
    must_exist: bool,
    kind: str,  # "file" | "dir"
    default: Path | None = None,
    allow_empty: bool = False,
) -> Path | None:
    """Loop until the user gives a path that satisfies ``must_exist`` + ``kind``.

    If ``allow_empty=True`` an empty answer returns ``None`` (skip the field).
    """
    default_str = str(default) if default is not None else None
    while True:
        raw = _prompt(question, default_str)
        if not raw:
            if allow_empty:
                return None
            print("  (a value is required)")
            continue
        path = Path(raw).expanduser().resolve()
        if must_exist:
            ok = path.is_file() if kind == "file" else path.is_dir()
            if not ok:
                print(f"  {kind} not found: {path}")
                continue
        return path


def _prompt_int_list(question: str, default: list[int]) -> list[int]:
    raw = _prompt(question, ",".join(str(c) for c in default))
    parts = [p.strip() for p in raw.replace(",", " ").split() if p.strip()]
    try:
        return [int(p) for p in parts]
    except ValueError:
        print(f"  invalid chapter list, keeping default {default}")
        return list(default)


# ---------------------------------------------------------------------------
# Auto-detection of repo-bundled KB
# ---------------------------------------------------------------------------


def _autodetect_kb_minimal() -> Path | None:
    """Look for ``kb_minimal/`` next to this package, then in CWD.

    Helps the typical "git clone + cd + uvx" flow where the user is already
    sitting at the repo root.
    """
    here = Path(__file__).resolve()
    # mcp/plantsim_mcp/build_kb_wizard.py → repo/mcp/plantsim_mcp → repo
    for candidate in (
        here.parent.parent.parent / "kb_minimal",
        Path.cwd() / "kb_minimal",
    ):
        if candidate.is_dir():
            return candidate.resolve()
    return None


# ---------------------------------------------------------------------------
# Interactive flow
# ---------------------------------------------------------------------------


_BANNER = """\
================================================================
 plantsim-copilot-mcp — init wizard
================================================================
This wizard creates ~/.plantsim-agent/config.toml so the MCP
server knows where to find your Plant Simulation knowledge.

You can skip anything optional (just press Enter). Re-run any
time to update the config.
"""


def run_interactive() -> WizardAnswers:
    """Interactively gather answers from stdin."""
    print(_BANNER)
    ans = WizardAnswers()

    # 1. KB roots
    print("\n[1/4] Markdown knowledge-base roots")
    print("      These get indexed for `search_help` and `get_api`.")
    auto = _autodetect_kb_minimal()
    if auto is not None:
        print(f"      Detected bundled `kb_minimal/` at: {auto}")
        if _prompt_yes_no("      Include it?", default=True):
            ans.help_kb_roots.append(auto)

    while True:
        prompt = (
            "      Add another KB root (path to a markdown dir)"
            if ans.help_kb_roots
            else "      Path to your first KB root (markdown dir)"
        )
        extra = _prompt_path(
            prompt, must_exist=True, kind="dir", allow_empty=bool(ans.help_kb_roots)
        )
        if extra is None:
            break
        if extra in ans.help_kb_roots:
            print("      (already added, skipping)")
            continue
        ans.help_kb_roots.append(extra)

    # 2. fullmd source
    print("\n[2/4] PTS Help full-markdown source (optional)")
    print("      A single docling-produced `*_full_docling_code_tagged.md`.")
    print("      Adds chapter-aware H5/H6 entries (Stop, Capacity, ...).")
    if _prompt_yes_no("      Configure a fullmd source now?", default=False):
        ans.fullmd_src = _prompt_path(
            "      Path to fullmd .md file",
            must_exist=True,
            kind="file",
            allow_empty=True,
        )
        if ans.fullmd_src is not None:
            ans.fullmd_chapters = _prompt_int_list(
                "      Chapter numbers to index",
                default=ans.fullmd_chapters,
            )

    # 3. default project
    print("\n[3/4] Default .psfm project (optional)")
    print("      Lets `build-project` run without --project, and acts as the")
    print("      default for `find_method` / `find_callers` / etc.")
    if _prompt_yes_no("      Configure a default project now?", default=False):
        ans.default_project = _prompt_path(
            "      Path to your .psfm folder",
            must_exist=True,
            kind="dir",
            allow_empty=True,
        )

    # 4. index dir
    print("\n[4/4] Index output directory")
    print("      Where `help.db` and `project.db` live.")
    new_dir = _prompt(
        "      Index directory (will be created if missing)",
        default=str(ans.index_dir),
    )
    ans.index_dir = Path(new_dir).expanduser().resolve()

    return ans


# ---------------------------------------------------------------------------
# Summary + build
# ---------------------------------------------------------------------------


def print_summary(ans: WizardAnswers) -> None:
    print("\n--- summary ---")
    print(f"  index_dir       : {ans.index_dir}")
    if ans.help_kb_roots:
        print("  help_kb_roots   :")
        for r in ans.help_kb_roots:
            print(f"    - {r}")
    else:
        print("  help_kb_roots   : (none)")
    print(f"  fullmd_src      : {ans.fullmd_src or '(none)'}")
    if ans.fullmd_src is not None:
        print(f"  fullmd_chapters : {ans.fullmd_chapters}")
    print(f"  default_project : {ans.default_project or '(none)'}")


def maybe_build(ans: WizardAnswers, *, run_build: bool) -> int:
    """If ``run_build``, invoke the same indexers the CLI subcommands use.

    Returns 0 on success or the number of failed steps.
    """
    if not run_build:
        return 0
    if not ans.help_kb_roots and ans.fullmd_src is None and ans.default_project is None:
        print("\n(nothing to build — skip)")
        return 0

    # Import lazily so the wizard itself stays import-cheap.
    from .indexers.help_md_to_fts import build
    from .indexers.pts_help_fullmd_indexer import build_fullmd
    from .storage.sqlite import SQLiteFTSIndex

    failures = 0
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if ans.help_kb_roots or ans.fullmd_src is not None:
        help_db = ans.index_dir / "help.db"
        print(f"\n[build] help index -> {help_db}")
        try:
            with SQLiteFTSIndex(help_db) as idx:
                idx.delete_all()
                prose = build(ans.help_kb_roots, idx) if ans.help_kb_roots else 0
                full = (
                    build_fullmd(ans.fullmd_src, idx, chapters=tuple(ans.fullmd_chapters))
                    if ans.fullmd_src is not None
                    else 0
                )
            print(f"  done — prose={prose}  fullmd={full}  total={prose + full}")
        except Exception as exc:  # noqa: BLE001 — surface any indexer failure
            failures += 1
            print(f"  FAILED: {exc}", file=sys.stderr)

    if ans.default_project is not None:
        from .indexers.psfm_indexer import build_project_index
        from .storage.project import ProjectStore

        project_db = ans.index_dir / "project.db"
        print(f"\n[build] project index -> {project_db}")
        try:
            with ProjectStore(project_db) as store:
                result = build_project_index(ans.default_project, store)
            print(
                f"  done — files={result.files_scanned} "
                f"objects={len(result.objects)} "
                f"code_units={len(result.code_units)} "
                f"edges={len(result.edges)}"
            )
        except Exception as exc:  # noqa: BLE001
            failures += 1
            print(f"  FAILED: {exc}", file=sys.stderr)

    return failures


# ---------------------------------------------------------------------------
# Entry — called from server.py CLI subparser
# ---------------------------------------------------------------------------


def cmd_init(args: argparse.Namespace) -> int:
    """``plantsim-copilot-mcp init`` entry point."""
    target_cfg = Path(args.config).expanduser().resolve() if args.config else (
        agent_home() / CONFIG_FILENAME
    )

    if args.non_interactive:
        ans = _build_non_interactive(args)
    else:
        if target_cfg.exists() and not args.force:
            print(f"Config already exists at {target_cfg}.")
            if not _prompt_yes_no("Overwrite?", default=False):
                print("Aborted.")
                return 1
        ans = run_interactive()

    print_summary(ans)

    if not args.non_interactive:
        confirm = _prompt_yes_no(f"\nWrite to {target_cfg}?", default=True)
        if not confirm:
            print("Aborted; nothing written.")
            return 1

    write_config(ans, target_cfg)
    print(f"\nWrote {target_cfg}")

    # Build step
    if args.non_interactive:
        run_build = args.build
    else:
        run_build = _prompt_yes_no(
            "\nBuild indices now? (uses the paths above)", default=True
        )
    fails = maybe_build(ans, run_build=run_build)

    if fails == 0:
        print("\nDone. Start the server with:")
        print("  plantsim-copilot-mcp serve")
    else:
        print(f"\nFinished with {fails} build error(s) — see messages above.")
    return 0 if fails == 0 else 1


def _build_non_interactive(args: argparse.Namespace) -> WizardAnswers:
    """Materialise WizardAnswers from CLI flags for scripted / test use."""
    ans = WizardAnswers()
    if args.kb_root:
        for r in args.kb_root:
            p = Path(r).expanduser().resolve()
            if not p.is_dir():
                raise SystemExit(f"--kb-root not a directory: {p}")
            ans.help_kb_roots.append(p)
    if args.fullmd_src:
        p = Path(args.fullmd_src).expanduser().resolve()
        if not p.is_file():
            raise SystemExit(f"--fullmd-src not a file: {p}")
        ans.fullmd_src = p
    if args.chapters:
        ans.fullmd_chapters = list(args.chapters)
    if args.project:
        p = Path(args.project).expanduser().resolve()
        if not p.is_dir():
            raise SystemExit(f"--project not a directory: {p}")
        ans.default_project = p
    if args.index_dir:
        ans.index_dir = Path(args.index_dir).expanduser().resolve()
    return ans


def add_init_subparser(subparsers: argparse._SubParsersAction) -> None:
    """Register the ``init`` subcommand on a parent ``argparse`` subparsers."""
    p = subparsers.add_parser(
        "init",
        help="interactive setup wizard — writes ~/.plantsim-agent/config.toml",
    )
    p.add_argument(
        "--config",
        default=None,
        help="write config to this path (default: ~/.plantsim-agent/config.toml)",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="overwrite an existing config without prompting",
    )
    p.add_argument(
        "--non-interactive",
        action="store_true",
        help="don't prompt — take everything from --kb-root / --fullmd-src / ... flags",
    )
    # Non-interactive flags (also harmless in interactive mode).
    p.add_argument(
        "--kb-root",
        action="append",
        default=None,
        help="markdown KB root (repeat). Required in --non-interactive mode if "
        "no other source given.",
    )
    p.add_argument(
        "--fullmd-src",
        default=None,
        help="path to PTS Help fullmd file (single .md)",
    )
    p.add_argument(
        "--chapters",
        type=lambda s: [int(p) for p in s.replace(",", " ").split() if p.strip()],
        default=None,
        help='chapters to index from --fullmd-src (e.g. "11,12,13,15")',
    )
    p.add_argument(
        "--project",
        default=None,
        help="default .psfm folder for find_method/find_callers/etc.",
    )
    p.add_argument(
        "--index-dir",
        default=None,
        help="where help.db / project.db are written (default: $PLANTSIM_AGENT_HOME/indices)",
    )
    p.add_argument(
        "--build",
        action="store_true",
        help="(--non-interactive only) run the indexers after writing config",
    )
